config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  root to: "static_pages#root"

  namespace :api, defaults: { format: :json } do
    resources :groups, except: [:new, :edit] do
      resources :events, only: [:create, :index]
    end
    resources :users_groups, only: [:create, :destroy, :index]
    resources :events, only: [:show, :destroy, :update]
  end

  resources :users, only: [:create, :new]
  resources :users, defaults: { format: :json }, only: [:show, :index]

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '*path' => redirect('/')
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  img_url         :string
#

class User < ActiveRecord::Base
  attr_reader :password
  after_initialize :ensure_session_token

  validates :email, :session_token, :password_digest,
      :name, presence: true
  validates :email, format: { with: /@/ }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :email, :session_token, uniqueness: true

  has_many :users_groups
  has_many :groups, through: :users_groups

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)

    return nil if user.nil?
    user && user.valid_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :ensure_login, only: [:index, :show]

  def create
    @user = User.new(user_params)

    if @user.save
      if @user.img_url.nil?
        @user.img_url = "23947837641_e5456f1850_m_voo3vr.jpg"
      end
      log_in!(@user)
      flash[:notice] = "Sign up successful."
      redirect_to :root
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    @users = User.all
    render json: @users
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :group_id, :event_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div class="login-page">
  <div class="login">
  <h2>Signup to Begin using<br />Entente<span class="glyphicon glyphicon-pushpin" /></h2>
  <h4>/änˈtänt/</h4><br /><h4>Find groups and events that match your interests.</h4>
  <br>
  <form action="<%= users_url %>" method="post">
    <%= auth_token %>
    <div class="form-group">
      <label for="user_name">Name</label>
      <br>
      <input
        type="text"
        name="user[name]"
        value="<%= @user.name %>"
        id="user_name">
    </div>
    <div class="form-group">
      <label for="user_email">Email</label>
      <br>
      <input
        type="text"
        name="user[email]"
        value="<%= @user.email %>"
        id="user_email">
    </div>
    <div class="form-group">
      <label for="user_password">Password</label>
      <br>
      <input type="password" name="user[password]" id="user_password">
    </div>
    <button type="submit" id="user" class="login-btn">Sign Up</button>
  </form>
  <br>
  <p class="intro-text">
    <%= link_to "Already have an account?  Log In!", login_url%>
  </p>
  </div>
  <p id="credit">tumblr @cathgarvey</p>
</div>